version: '3'  
services:
  myapp:
    build:
      context: .  
      dockerfile: Dockerfile  
    image: encore-pg:latest
    container_name: encore-pg-container
    volumes:
      - "${HOST_MOUNT_PATH}:/usr/src/app"